version: "3.8"

services:
  # NestJS Todo API
  api:
    build:
      dockerfile: Dockerfile
      context: ./kanban-api
      # Only build development stage from our dockerfile
      target: development
    volumes:
      - ./kanban-api:/lucas/src/app
      - /lucas/src/app/node_modules
    # dev mode: npm run start:dev / debug: npm run start:debug
    command: npm run start:dev
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
    ports:
      - "3000:3000"
  postgres:
    image: postgres:14.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 35000:5432
  postgres_admin:
    image: dpage/pgadmin4:6.12
    depends_on:
    - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80
